name: nckrig
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11.0
  - pykrige>=1.7.0
  - tqdm>=4.64.1
  - numpy>=1.23.5
  - xarray>=2022.11.0
  - netcdf4>=1.6.2
  - matplotlib>=3.7.1